---  
  - name: "install NodeJS 13.8.0"
    become: true
    shell: |
      sudo apt update
      sudo apt upgrade
      sudo apt install nodejs
      
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
  