---  
  - name: "Create backend DIR"
    file: 
      path: ~/backend 
      state: directory
  
  - name: "Copy files"
    become: true
    shell: |
      cp artifact.tar.gz ~/backend
  
  - name: "Unarchive backend files"
    shell: |
      cd ~/backend
      tar xvzf artifact.tar.gz -C .

  - name: "Installing Node Dependencies"
    shell: |
      cd ~/backend
      npm i

  - name: "Executing Node app with PM2"
    shell: |
      cd ~/backend/dist
      pm2 stop default
      pm2 start main.js

    register: execute_node

  - name: print message
    debug:
      msg: "{{ execute_node.stdout_lines }}"

  - name: "Configure pm2 to start as service"
    shell: |
      sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
      pm2 save
    